# 1. Preliminary

## 1.1 Context



<table style="left:0; font-size:1.5rem">
    <tbody>
        <tr>
            <td>Cours</td>
            <td>Entraînez un modèle prédictif linéaire</td>
        </tr>
        <tr>
            <td>TP</td>
            <td>TP - Entraînez une régression logistique et une SVM linéaire</td>
        </tr>
        <tr>
            <td>Notebook</td>
            <td>2/2 Modelisation</td>
        </tr>
        <tr>
            <td>Date</td>
            <td>Juillet 2022</td>
        </tr>
        <tr>
            <td>Auteur</td>
            <td>Alexandre Gazagnes </td>
        </tr>
        <tr>
            <td>Source</td>
            <td><a href=https://www.kaggle.com/datasets/uciml/mushroom-classification>https://www.kaggle.com/datasets/uciml/mushroom-classification</a></td>
        </tr>
    </tbody>
</table>

<img src="img/kaggle.png"
     alt="img/kaggle.png" />

## 1.2 Requirements

* pandas
* numpy


* scikit-learn


* matplotlib

In [1]:
package_list = ("pandas", "numpy", "scikit-learn", "matplotlib")

In [2]:
!python3 -V

Python 3.10.5


In [3]:
txt = !python3 -m pip freeze
check = lambda i : any([(pack in i) for pack in package_list]) 
txt = [i for i in txt if check(i)]
txt

['matplotlib==3.5.2',
 'matplotlib-inline==0.1.3',
 'numpy==1.23.0',
 'pandas==1.4.3',
 'scikit-learn==1.1.1']

## 1.3 Imports

In [4]:
# builtin 
import os, warnings


# data
import pandas as pd
import numpy as np


# preprocessing
from sklearn.preprocessing import LabelEncoder
# metrics
from sklearn.metrics import roc_curve, auc, confusion_matrix
# estimators
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
# model selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
# metrics
from sklearn.metrics import roc_curve, auc

# visualisation
import matplotlib.pyplot as plt


## 1.4 Graphics and options

In [ ]:
# warnings.filterwarnings('ignore')
warnings.filterwarnings(action='once')

<div class="alert alert-info" role="alert">
  Nous désactivons les messages d'erreurs </div>

## 1.5 Data

<img src="img/tree.jpg"
     alt="img/tree.jpg" />

<div class="alert alert-info" role="alert">
  Une bonne organisation de dossiers / fichiers vous évitera bien des problèmes!
</div>

In [5]:
os.listdir()

['.DS_Store',
 '00_EDA.ipynb',
 'requirements.txt',
 'env',
 'img',
 '.ipynb_checkpoints',
 'data',
 '01_modelisation.ipynb']

In [6]:
path     = "./data/cleaned/"        
filename = "df_cleaned.csv"   

In [7]:
df = pd.read_csv(path + filename)
df.head()

target  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0       1          5            2          4        1     6                1   
1       0          5            2          9        1     0                1   
2       0          0            2          8        1     3                1   
3       1          5            3          8        1     6                1   
4       0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-above-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
0                         2                       7                       7   
1                         2                       7                       7   
2                         2                       7                       7   
3                         2                       7                       7   
4                         2                       7                       7   

   veil-color  ring-number  ring-type  spore-print-color  population  habitat  
0           2            1          4                  2           3        5  
1           2            1          4                  3           2        1  
2           2            1          4                  3           2        3  
3           2            1          4                  2           3        5  
4           2            1          0                  3           0        1  

[5 rows x 22 columns]

# 2. Data preparation

## 2.1 X & y

In [8]:
X = df.drop(columns="target")
y = df.target

In [9]:
X.head()

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0          5            2          4        1     6                1   
1          5            2          9        1     0                1   
2          0            2          8        1     3                1   
3          5            3          8        1     6                1   
4          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0             0          1           4            0  ...   
1             0          0           4            0  ...   
2             0          0           5            0  ...   
3             0          1           5            0  ...   
4             1          0           4            1  ...   

   stalk-surface-above-ring  stalk-surface-below-ring  stalk-color-above-ring  \
0                         2                         2                       7   
1                         2                         2                       7   
2                         2                         2                       7   
3                         2                         2                       7   
4                         2                         2                       7   

   stalk-color-below-ring  veil-color  ring-number  ring-type  \
0                       7           2            1          4   
1                       7           2            1          4   
2                       7           2            1          4   
3                       7           2            1          4   
4                       7           2            1          0   

   spore-print-color  population  habitat  
0                  2           3        5  
1                  3           2        1  
2                  3           2        3  
3                  2           3        5  
4                  3           0        1  

[5 rows x 21 columns]

In [10]:
y.head()

0    1
1    0
2    0
3    1
4    0
Name: target, dtype: int64

## 2.2 Test train split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.3, 
                                                    random_state=42)

In [12]:
print(f"Nous avons X_train de forme {X_train.shape} et y_train de forme  {y_train.shape}  ")
print(f"Nous avons X_test de forme {X_test.shape} et y_test de forme  {y_test.shape}  ")

Nous avons X_train de forme (5686, 21) et y_train de forme  (5686,)  
Nous avons X_test de forme (2438, 21) et y_test de forme  (2438,)  


# 3. Modelisation

## 3.1 Dummy classifier

In [13]:
estimator = DummyClassifier(strategy="most_frequent")
estimator.fit(X_train, y_train)

DummyClassifier(strategy='most_frequent')

In [14]:
y_pred = estimator.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
pd.Series(y_pred).value_counts()

0    2438
dtype: int64

In [16]:
y_test.value_counts(normalize=True)

0    0.515587
1    0.484413
Name: target, dtype: float64

In [17]:
y_test.values

array([0, 1, 1, ..., 1, 0, 0])

In [18]:
tr_score = estimator.score(X_train, y_train).round(4)
te_score = estimator.score(X_test, y_test).round(4)

print(f"score train : {tr_score} score test : {te_score} ")

score train : 0.519 score test : 0.5156 


In [19]:
def score(estimator):
    """compute and print train score and test score"""
    
    tr_score = estimator.score(X_train, y_train).round(4)
    te_score = estimator.score(X_test, y_test).round(4)

    print(f"score train : {tr_score} score test : {te_score} ")

In [20]:
score(estimator)

score train : 0.519 score test : 0.5156 


In [21]:
pd.Series(y_train).value_counts(normalize=True).round(4)

0    0.519
1    0.481
Name: target, dtype: float64

In [22]:
pd.Series(y_test).value_counts(normalize=True).round(4)

0    0.5156
1    0.4844
Name: target, dtype: float64

In [23]:
mat = confusion_matrix(y_test, y_pred)
mat

array([[1257,    0],
       [1181,    0]])

In [24]:
mat = pd.DataFrame(mat)
mat

0  1
0  1257  0
1  1181  0

In [25]:
mat = pd.DataFrame(mat)
mat.columns = [f"pred_{i}" for i in mat.columns]
mat.index = [f"test_{i}" for i in mat.index]
mat

pred_0  pred_1
test_0    1257       0
test_1    1181       0

In [26]:
def confusion(y_test, y_pred) : 
    """display a fancy confusion matrix """

    mat = confusion_matrix(y_test, y_pred)
    mat = pd.DataFrame(mat)
    mat.columns = [f"pred_{i}" for i in mat.columns]
    mat.index = [f"test_{i}" for i in mat.index]
    
    return mat

In [27]:
confusion(y_test, y_pred)

pred_0  pred_1
test_0    1257       0
test_1    1181       0

In [ ]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc

In [ ]:
plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

## 3.2 Simple Logistic regression & Linear SVM

### 3.2.1  Logistic Regression

In [28]:
estimator = LogisticRegression(solver="liblinear")
estimator.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [29]:
y_pred = estimator.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0])

In [30]:
y_prob = estimator.predict_proba(X_test).round(2)
y_prob

array([[1.  , 0.  ],
       [0.09, 0.91],
       [0.  , 1.  ],
       ...,
       [0.09, 0.91],
       [1.  , 0.  ],
       [0.96, 0.04]])

In [31]:
score(estimator)
confusion(y_test, y_pred)

score train : 0.9488 score test : 0.9491 


pred_0  pred_1
test_0    1201      56
test_1      68    1113

In [ ]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate).round(2)
print(roc_auc)

In [ ]:

plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

### 3.2.2 SVM

In [34]:
estimator = LinearSVC()
estimator.fit(X_train, y_train)

/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [35]:
y_pred = estimator.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0])

In [36]:
y_prob = estimator.predict_proba(X_test).round(2)
y_prob

AttributeError: 'LinearSVC' object has no attribute 'predict_proba'

In [37]:
score(estimator)
confusion(y_test, y_pred)

score train : 0.9509 score test : 0.9508 


pred_0  pred_1
test_0    1199      58
test_1      62    1119

In [ ]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate).round(2)
print(roc_auc)

In [ ]:

plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

## 3.3. Finding Hyper-parameters

### 3.3.1 Logistic Regression

In [38]:
estimator = LogisticRegression()

params = {  'C': np.logspace(-3, 3, 7) , 
            'penalty':['l1','l2'], 
            'solver' : ['newton-cg', 'lbfgs', 'liblinear']
         }

In [39]:
grid = GridSearchCV(estimator, 
                    params, 
                    cv=10, 
                    n_jobs=-1, 
                    return_train_score=True, 
                    verbose=1)

grid.fit(X_train, y_train)

Fitting 10 folds for each of 42 candidates, totalling 420 fits


/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also re

/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also re

/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also re

/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/mod

GridSearchCV(cv=10, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear']},
             return_train_score=True, verbose=1)

In [40]:
best_params = grid.best_params_
best_params

{'C': 1000.0, 'penalty': 'l2', 'solver': 'liblinear'}

In [41]:
res = grid.cv_results_
res

{'mean_fit_time': array([4.45933342e-03, 3.65517139e-03, 2.18547106e-02, 1.19077992e-01,
        6.87489986e-02, 4.10819292e-02, 2.76441574e-03, 1.57752037e-03,
        2.01554060e-01, 1.69447184e-01, 1.58359766e-01, 6.50650978e-02,
        2.22406387e-03, 1.59726143e-03, 4.77758121e-01, 2.77023315e-01,
        2.03966355e-01, 1.17266250e-01, 1.82838440e-03, 2.17046738e-03,
        1.22751621e+01, 4.48527169e-01, 2.37798572e-01, 1.75065303e-01,
        4.65648174e-03, 1.70886517e-03, 1.52605901e+01, 6.04115009e-01,
        1.80520010e-01, 2.24207425e-01, 1.88903809e-03, 2.65612602e-03,
        1.68209342e+01, 7.81593227e-01, 2.02429724e-01, 3.43063688e-01,
        1.54185295e-03, 1.33554935e-03, 1.48536688e+01, 9.96593690e-01,
        1.50567412e-01, 3.68736458e-01]),
 'std_fit_time': array([3.86186654e-03, 2.97446827e-03, 2.11343676e-03, 1.69478876e-02,
        9.12708107e-03, 7.42569309e-03, 1.35756495e-03, 4.59111215e-04,
        5.51774652e-02, 2.60704265e-02, 5.14641218e-02, 1.823

In [42]:
res = grid.cv_results_
res = pd.DataFrame(res)
res

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.004459      0.003862         0.000000        0.000000   0.001   
1        0.003655      0.002974         0.000000        0.000000   0.001   
2        0.021855      0.002113         0.004187        0.001976   0.001   
3        0.119078      0.016948         0.004076        0.001957   0.001   
4        0.068749      0.009127         0.003581        0.001672   0.001   
5        0.041082      0.007426         0.004260        0.001927   0.001   
6        0.002764      0.001358         0.000000        0.000000    0.01   
7        0.001578      0.000459         0.000000        0.000000    0.01   
8        0.201554      0.055177         0.004387        0.001774    0.01   
9        0.169447      0.026070         0.003241        0.001414    0.01   
10       0.158360      0.051464         0.002946        0.000712    0.01   
11       0.065065      0.018231         0.003050        0.002101    0.01   
12       0.002224      0.001331         0.000000        0.000000     0.1   
13       0.001597      0.000807         0.000000        0.000000     0.1   
14       0.477758      0.096919         0.004941        0.001977     0.1   
15       0.277023      0.038377         0.007130        0.005905     0.1   
16       0.203966      0.022576         0.006194        0.008402     0.1   
17       0.117266      0.020759         0.011993        0.019296     0.1   
18       0.001828      0.001244         0.000000        0.000000     1.0   
19       0.002170      0.001099         0.000000        0.000000     1.0   
20      12.275162      1.308665         0.004425        0.002244     1.0   
21       0.448527      0.072509         0.005495        0.003788     1.0   
22       0.237799      0.032186         0.003402        0.001981     1.0   
23       0.175065      0.050070         0.005089        0.006536     1.0   
24       0.004656      0.007219         0.000000        0.000000    10.0   
25       0.001709      0.000510         0.000000        0.000000    10.0   
26      15.260590      3.158515         0.004570        0.002392    10.0   
27       0.604115      0.068465         0.004506        0.002929    10.0   
28       0.180520      0.035927         0.003324        0.001291    10.0   
29       0.224207      0.026084         0.006461        0.006032    10.0   
30       0.001889      0.001622         0.000000        0.000000   100.0   
31       0.002656      0.001033         0.000000        0.000000   100.0   
32      16.820934      3.444545         0.005820        0.006732   100.0   
33       0.781593      0.114450         0.004084        0.002391   100.0   
34       0.202430      0.037380         0.007596        0.011835   100.0   
35       0.343064      0.069061         0.005870        0.005652   100.0   
36       0.001542      0.000404         0.000000        0.000000  1000.0   
37       0.001336      0.000224         0.000000        0.000000  1000.0   
38      14.853669      4.090008         0.009027        0.014769  1000.0   
39       0.996594      0.104796         0.011785        0.012956  1000.0   
40       0.150567      0.031399         0.004442        0.002570  1000.0   
41       0.368736      0.082850         0.004264        0.002075  1000.0   

   param_penalty param_solver  \
0             l1    newton-cg   
1             l1        lbfgs   
2             l1    liblinear   
3             l2    newton-cg   
4             l2        lbfgs   
5             l2    liblinear   
6             l1    newton-cg   
7             l1        lbfgs   
8             l1    liblinear   
9             l2    newton-cg   
10            l2        lbfgs   
11            l2    liblinear   
12            l1    newton-cg   
13            l1        lbfgs   
14            l1    liblinear   
15            l2    newton-cg   
16            l2        lbfgs   
17            l2    liblinear   
18            l1    newton-cg   
19            l1        lbfgs   
20            l1    liblinear   
21       

In [43]:
cols = [i for i in res.columns if "split" not in i]
cols

['mean_fit_time',
 'std_fit_time',
 'mean_score_time',
 'std_score_time',
 'param_C',
 'param_penalty',
 'param_solver',
 'params',
 'mean_test_score',
 'std_test_score',
 'rank_test_score',
 'mean_train_score',
 'std_train_score']

In [44]:
res = res[cols]
res = res.sort_values("rank_test_score")
res.head(10)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
41       0.368736      0.082850         0.004264        0.002075  1000.0   
39       0.996594      0.104796         0.011785        0.012956  1000.0   
33       0.781593      0.114450         0.004084        0.002391   100.0   
38      14.853669      4.090008         0.009027        0.014769  1000.0   
26      15.260590      3.158515         0.004570        0.002392    10.0   
32      16.820934      3.444545         0.005820        0.006732   100.0   
35       0.343064      0.069061         0.005870        0.005652   100.0   
40       0.150567      0.031399         0.004442        0.002570  1000.0   
27       0.604115      0.068465         0.004506        0.002929    10.0   
34       0.202430      0.037380         0.007596        0.011835   100.0   

   param_penalty param_solver  \
41            l2    liblinear   
39            l2    newton-cg   
33            l2    newton-cg   
38            l1    liblinear   
26            l1    liblinear   
32            l1    liblinear   
35            l2    liblinear   
40            l2        lbfgs   
27            l2    newton-cg   
34            l2        lbfgs   

                                               params  mean_test_score  \
41  {'C': 1000.0, 'penalty': 'l2', 'solver': 'libl...         0.960428   
39  {'C': 1000.0, 'penalty': 'l2', 'solver': 'newt...         0.960427   
33  {'C': 100.0, 'penalty': 'l2', 'solver': 'newto...         0.959900   
38  {'C': 1000.0, 'penalty': 'l1', 'solver': 'libl...         0.959548   
26  {'C': 10.0, 'penalty': 'l1', 'solver': 'liblin...         0.959548   
32  {'C': 100.0, 'penalty': 'l1', 'solver': 'libli...         0.959372   
35  {'C': 100.0, 'penalty': 'l2', 'solver': 'libli...         0.959020   
40  {'C': 1000.0, 'penalty': 'l2', 'solver': 'lbfgs'}         0.953920   
27  {'C': 10.0, 'penalty': 'l2', 'solver': 'newton...         0.953744   
34   {'C': 100.0, 'penalty': 'l2', 'solver': 'lbfgs'}         0.953394   

    std_test_score  rank_test_score  mean_train_score  std_train_score  
41        0.012545                1          0.961836         0.003616  
39        0.012621                2          0.961993         0.003726  
33        0.012461                3          0.961289         0.003506  
38        0.012163                4          0.961231         0.003727  
26        0.012318                5          0.960918         0.003629  
32        0.012650                6          0.961016         0.003710  
35        0.012593                7          0.960859         0.003555  
40        0.010497                8          0.955622         0.002217  
27        0.011106                9          0.954958         0.002697  
34        0.010822               10          0.955915         0.002975

In [45]:
def resultize(grid) : 
    """make a fancy df from grid.cv_results"""

    res = grid.cv_results_
    res = pd.DataFrame(res)
    cols = [i for i in res.columns if "split" not in i]
    res = res[cols]
    res = res.sort_values("rank_test_score")    
    
    return res

In [46]:
resultize(grid).head(10)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
41       0.368736      0.082850         0.004264        0.002075  1000.0   
39       0.996594      0.104796         0.011785        0.012956  1000.0   
33       0.781593      0.114450         0.004084        0.002391   100.0   
38      14.853669      4.090008         0.009027        0.014769  1000.0   
26      15.260590      3.158515         0.004570        0.002392    10.0   
32      16.820934      3.444545         0.005820        0.006732   100.0   
35       0.343064      0.069061         0.005870        0.005652   100.0   
40       0.150567      0.031399         0.004442        0.002570  1000.0   
27       0.604115      0.068465         0.004506        0.002929    10.0   
34       0.202430      0.037380         0.007596        0.011835   100.0   

   param_penalty param_solver  \
41            l2    liblinear   
39            l2    newton-cg   
33            l2    newton-cg   
38            l1    liblinear   
26            l1    liblinear   
32            l1    liblinear   
35            l2    liblinear   
40            l2        lbfgs   
27            l2    newton-cg   
34            l2        lbfgs   

                                               params  mean_test_score  \
41  {'C': 1000.0, 'penalty': 'l2', 'solver': 'libl...         0.960428   
39  {'C': 1000.0, 'penalty': 'l2', 'solver': 'newt...         0.960427   
33  {'C': 100.0, 'penalty': 'l2', 'solver': 'newto...         0.959900   
38  {'C': 1000.0, 'penalty': 'l1', 'solver': 'libl...         0.959548   
26  {'C': 10.0, 'penalty': 'l1', 'solver': 'liblin...         0.959548   
32  {'C': 100.0, 'penalty': 'l1', 'solver': 'libli...         0.959372   
35  {'C': 100.0, 'penalty': 'l2', 'solver': 'libli...         0.959020   
40  {'C': 1000.0, 'penalty': 'l2', 'solver': 'lbfgs'}         0.953920   
27  {'C': 10.0, 'penalty': 'l2', 'solver': 'newton...         0.953744   
34   {'C': 100.0, 'penalty': 'l2', 'solver': 'lbfgs'}         0.953394   

    std_test_score  rank_test_score  mean_train_score  std_train_score  
41        0.012545                1          0.961836         0.003616  
39        0.012621                2          0.961993         0.003726  
33        0.012461                3          0.961289         0.003506  
38        0.012163                4          0.961231         0.003727  
26        0.012318                5          0.960918         0.003629  
32        0.012650                6          0.961016         0.003710  
35        0.012593                7          0.960859         0.003555  
40        0.010497                8          0.955622         0.002217  
27        0.011106                9          0.954958         0.002697  
34        0.010822               10          0.955915         0.002975

In [47]:
estimator = LogisticRegression(penalty="l2", C=1000, solver='liblinear')
estimator

LogisticRegression(C=1000, solver='liblinear')

In [48]:
estimator = LogisticRegression(**best_params)
estimator

LogisticRegression(C=1000.0, solver='liblinear')

In [49]:
estimator = LogisticRegression(**best_params)
estimator.fit(X_train, y_train)
y_pred = estimator.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0])

In [50]:
score(estimator)
confusion(y_test, y_pred)

score train : 0.9618 score test : 0.9623 


pred_0  pred_1
test_0    1209      48
test_1      44    1137

In [51]:
1/5

0.2

In [ ]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate).round(2)
print(roc_auc)

In [ ]:
plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()

### 3.3.2 SVM

In [52]:
estimator = LinearSVC()

params = { 'C': np.logspace(-3, 3, 7) }

In [53]:
grid = GridSearchCV(estimator, 
                    params, 
                    cv=10, 
                    n_jobs=-1, 
                    return_train_score=True, 
                    verbose=1)

grid.fit(X_train, y_train)

Fitting 10 folds for each of 7 candidates, totalling 70 fits


/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre

/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/alexandre

GridSearchCV(cv=10, estimator=LinearSVC(), n_jobs=-1,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])},
             return_train_score=True, verbose=1)

In [54]:
print(grid.best_params_)

{'C': 1.0}


In [55]:
resultize(grid).head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
3       1.158993      0.090387         0.003655        0.001072     1.0   
2       1.107012      0.107633         0.004835        0.003141     0.1   
5       1.087865      0.032372         0.002439        0.000435   100.0   
1       0.119906      0.011118         0.003376        0.000603    0.01   
6       0.985701      0.073355         0.002589        0.000711  1000.0   

          params  mean_test_score  std_test_score  rank_test_score  \
3     {'C': 1.0}         0.946360        0.009308                1   
2     {'C': 0.1}         0.945654        0.008276                2   
5   {'C': 100.0}         0.940378        0.013391                3   
1    {'C': 0.01}         0.936686        0.006242                4   
6  {'C': 1000.0}         0.933173        0.020524                5   

   mean_train_score  std_train_score  
3          0.948333         0.004786  
2          0.947493         0.001389  
5          0.941885         0.011380  
1          0.938230         0.002168  
6          0.935025         0.017394

In [56]:
estimator = LinearSVC(**grid.best_params_)
estimator.fit(X_train, y_train)

/Users/alexandre.gazagnes/Desktop/cours/fr/entrainez-un-modele-lineaire/partie-2/tp/env/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [57]:
y_pred = estimator.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 0, 0])

In [58]:
score(estimator)
confusion(y_test, y_pred)

score train : 0.9516 score test : 0.9532 


pred_0  pred_1
test_0    1196      61
test_1      53    1128

In [ ]:
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(false_positive_rate, true_positive_rate).round(2)
print(roc_auc)

In [ ]:
plt.figure(figsize=(10,10))
plt.title('Receiver Operating Characteristic')
plt.plot(false_positive_rate,true_positive_rate, color='red',label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],linestyle='--')
plt.axis('tight')
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()